/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/scene.gltf 
Author: bhaveshchalke4513 (https://sketchfab.com/bhaveshchalke4513)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-area-7604da04e6f34f8b8c0178084a161570
Title: COMPUTER-DESK-AREA
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { Avatar } from "./Avatar";

export function Desk(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/computer-desk-area/scene.gltf"
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Body108_0"
                position={[-0.724, 0.86, 0.657]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_4" // Virtual Glass
                  geometry={nodes.Object_4.geometry}
                  material={materials.material}
                />
              </group>
              <group
                name="Cube_1" // Virtual glass grey cube
                position={[-0.724, 0.86, 0.762]}
                scale={0.092}
              >
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="MONITOR_4"
                position={[0.048, 0.77, 0.305]}
                scale={0.605}
              >
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.peopleColors}
                />
                <mesh
                  name="Object_9"
                  geometry={nodes.Object_9.geometry}
                  material={materials.material_3}
                />
              </group>
              <group
                name="TABLE_5"
                position={[0.048, -0.15, 0.47]}
                scale={0.605}
              >
                <mesh
                  name="Object_11"
                  geometry={nodes.Object_11.geometry}
                  material={materials.WOOD}
                />
              </group>
              <group
                name="KEYBOARD_6"
                position={[-0.15, 0.8, 0.7]}
                scale={0.605}
              >
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials.peopleColors}
                />
              </group>
              <group name="MOUSE_7" position={[0.35, 0.78, 0.6]}>
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials.peopleColors}
                />
              </group>
              <group
                name="Cylinder002_8"
                position={[0.011, 0.48, 1.2]}
                scale={[0.026, 0.245, 0.026]}
              >
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials.peopleColors}
                />
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials.FABRIC}
                />
              </group>
              <group
                name="Cylinder003_9"
                position={[0.011, 0.4, 1.214]}
                scale={[0.026, 0.245, 0.026]}
              >
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials.FABRIC}
                />
              </group>
              <group
                name="Cylinder007_10"
                position={[0.011, 0.43, 1.214]}
                scale={[0.026, 0.245, 0.026]}
              >
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials.peopleColors}
                />
              </group>
              <group
                name="MONITOR001_11"
                position={[0.808, 1.08, 0.49]}
                scale={0.605}
              >
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials.material_6}
                />
              </group>
              <group
                name="rig_CharRoot_43"
                position={[0, -0.199, 1.224]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.01}
              >
                <group
                  name="bip_42"
                  position={[0, 92.405, -1.666]}
                  rotation={[0, -1.571, 0]}
                >
                  {/* <Avatar
                    animation={props.animation}
                    position={[0, 0, 0]}
                    rotation={[0, Math.PI, 0]}
                    scale={[1, 1, 1]}
                  /> */}

                  {/* <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="lpMaleG_41" />
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={materials.peopleColors}
                      skeleton={nodes.Object_30.skeleton}
                    />
                    <skinnedMesh
                      name="Object_31"
                      geometry={nodes.Object_31.geometry}
                      material={materials.peopleColors}
                      skeleton={nodes.Object_31.skeleton}
                    />
                  </group> */}
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/computer-desk-area/scene.gltf");
